services:
  db:
    image: postgres:alpine
    container_name: testdb
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: db
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db  # Use service name as the hostname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: db
      POSTGRES_DB: testdb
      DB_PORT: 5432
      PORT: 3000

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata: